# -*- coding: utf-8 -*-
RETIRED = {
    'TC-ADMIN-001': 'Trùng TC-ADMIN-013 (báo cáo bài viết)',
    'TC-ADMIN-002': 'Trùng TC-ADMIN-039 (mod ẩn bài) và nhóm TC-ADM2 Nội dung (admin gỡ nội dung)',
    'TC-ADMIN-003': 'Trùng nhóm TC-ADM (Người dùng: tạm ngưng/cấm toàn nền tảng, thu hồi phiên - cũng thay TC-ADMIN-076)',
    'TC-ADMIN-004': 'Trùng TC-ADMIN-058 + nhóm TC-ADM (Cộng đồng: tạm ngưng/xóa/khôi phục)',
    'TC-ADMIN-005': 'Trùng nhóm TC-SEARCH (tìm toàn cục: khóa học, thành viên, bài viết)',
    'TC-ADMIN-007': 'Trùng TC-ADM-038..057 (Bảng điều khiển) và TC-ADMIN-074',
    'TC-ADMIN-008': 'Trùng TC-ADMIN-052 (bỏ ẩn bài) và TC-ADM2 (khôi phục nội dung gỡ)',
    'TC-ADMIN-009': 'Trùng nhóm TC-ADM Audit log (/admin/audit-logs đã làm, ghi người/hành động/đối tượng)',
    'TC-ADMIN-010': 'Trùng TC-SEARCH-028/045 (tìm kiếm tôn trọng quyền riêng tư)',
    'TC-ADMIN-011': 'Trùng TC-ADMIN-056 và TC-ADM-008 (chỉ nhân viên admin vào /admin)',
    'TC-AUTH-021': 'Tính năng đã làm; trùng TC-AUTH-102 (thư reset trong outbox, link 30 phút) và TC-AUTH-115 (UI /forgot-password) - backend/docs/api/identity.md',
    'TC-AUTH-022': 'Tính năng đã làm; trùng TC-AUTH-108/109/113/114 (đặt lại mật khẩu, token một lần, hết hạn 30 phút, UI /reset-password)',
    'TC-AUTH-023': 'Tính năng đã làm; trùng TC-AUTH-076 (UI /settings tab Hồ sơ) và TC-AUTH-082 (avatar /files)',
    'TC-AUTH-034': "Tiêu đề khẳng định giới hạn 'tính theo tài khoản, không chặn nhầm người khác cùng IP' nhưng hành vi hiện tại là giới hạn THEO IP (auth.routes.ts loginLimiter, không có keyGenerator; xem TC-SEC-039/055); Playwright đã Pass bằng cách khẳng định 429 (ngược tiêu đề). Thay bằng case 'Giới hạn đăng nhập sai tính theo IP...' cuối module",
    'TC-COMM-001': 'Trùng TC-COMM-047 (người tạo thành Owner) và TC-COMM-050/052 (tạo cộng đồng UI)',
    'TC-COMM-002': 'Trùng TC-COMM-037/038/039 (validate tên cộng đồng)',
    'TC-COMM-003': 'Trùng TC-COMM-046 (pricing free) / TC-COMM-052 / TC-COMM-078 (tham gia công khai miễn phí)',
    'TC-COMM-004': 'Trùng TC-COMM-046 (pricing paid) / TC-COMM-079 (402 PAYMENT_REQUIRED)',
    'TC-COMM-005': 'Trùng TC-COMM-060 (công khai -> riêng tư) / TC-COMM-081 (riêng tư: JOIN_REQUEST_REQUIRED)',
    'TC-COMM-006': 'Trùng TC-FEED-119 (bảng tin theo thời gian, ghim trước) và các case FEED UI',
    'TC-COMM-007': "Tên tab nay là 'Lớp học' (không còn tab 'Khóa học' ở khu cộng đồng; sidebar: Cộng đồng/Lớp học/Lịch sự kiện/Thành viên/Bảng xếp hạng/Giới thiệu - CommunitySidebar.tsx); trùng TC-COURSE-027 và nhóm TC-SPLIT (chọn khóa ?khoa=)",
    'TC-COMM-008': 'Trùng TC-EVENT-030/034 (tab Lịch sự kiện)',
    'TC-COMM-009': 'Trùng TC-MEMBER-013/028 (tab Thành viên)',
    'TC-COMM-011': 'Trùng TC-COMM-078 (POST /enroll vào cộng đồng công khai miễn phí)',
    'TC-COMM-012': 'Trùng TC-COMM-079 (402 PAYMENT_REQUIRED) và TC-PAY-027..043 (luồng checkout)',
    'TC-COMM-013': 'Trùng TC-COMM-085 (gửi yêu cầu tham gia cộng đồng riêng tư)',
    'TC-COMM-014': 'Trùng TC-COMM-094 (Owner duyệt yêu cầu)',
    'TC-COMM-015': 'Trùng TC-COMM-095 (Owner từ chối yêu cầu)',
    'TC-COMM-016': 'Trùng TC-COMM-109 (nhận lời mời DEMO-VALID)',
    'TC-COMM-017': 'Trùng TC-COMM-147 (thành viên tự rời cộng đồng)',
    'TC-COMM-018': 'Trùng TC-COMM-129/130 (kick thành viên theo bậc)',
    'TC-COMM-019': 'Trùng TC-COMM-121 (Owner cấp quyền Admin)',
    'TC-COMM-020': 'Trùng TC-COMM-119/122 (bỏ Mod/Admin về Member)',
    'TC-COMM-021': 'Trùng TC-PAY-206 (Admin/Mod của chính cộng đồng không xem được doanh thu) và TC-ROLE-049',
    'TC-COMM-022': 'Trùng TC-HOME-001..017 (tìm kiếm/lọc Khám phá) và nhóm TC-SEARCH',
    'TC-COMM-023': 'Trùng TC-COMM-053/062 (admin sửa tên/mô tả/ảnh bìa)',
    'TC-COMM-024': 'Trùng TC-PAY-019 (cùng câu hỏi chính sách đổi giá, chưa chốt) và TC-COMM-059/TC-PAY-216 (hành vi hiện tại: không ảnh hưởng gói đang thuê)',
    'TC-COMM-025': 'Trùng TC-COMM-063/065 (xóa mềm cộng đồng + gõ lại tên)',
    'TC-COMM-027': 'Trùng TC-COMM-142 (chuyển quyền Owner)',
    'TC-COMM-028': 'Trùng TC-FEED-140 (người chưa tham gia 403) và TC-COMMVP-026 (FE chuyển về trang giới thiệu)',
    'TC-COMM-029': 'Trùng TC-COMM-105 (DEMO-EXPIRED: 410 INVITE_EXPIRED)',
    'TC-COMM-030': 'Trùng TC-COMM-107/113 (lời mời hết lượt: 410 INVITE_EXHAUSTED)',
    'TC-COMM-032': 'Trùng TC-COMM-149 (Owner không rời được: 409)',
    'TC-COMMVP-001': 'Trùng TC-FEED-019/021 (đăng bài)',
    'TC-COMMVP-002': 'Trùng TC-FEED-140 (người chưa tham gia 403)',
    'TC-COMMVP-003': 'Trùng TC-FEED-097 (tự like không điểm)',
    'TC-COMMVP-004': 'Trùng TC-FEED-083 (bình luận)',
    'TC-COMMVP-005': 'Trùng TC-FEED-077/078 (ghim chỉ mod+)',
    'TC-COMMVP-006': 'Trùng TC-FEED-119..128 (lọc/sắp xếp bài)',
    'TC-COMMVP-007': "Trùng TC-COURSE-021..026 (module/tiến độ; mô tả cũ 'module tự sinh từ course.lessons' đã lỗi thời - nay là nội dung lớp học thật trong DB)",
    'TC-COMMVP-008': 'Trùng TC-COURSE-052/053 (khóa module tuần tự)',
    'TC-COMMVP-009': 'Trùng TC-COURSE-057 (MODULE_LOCKED)',
    'TC-COMMVP-010': 'Trùng TC-COURSE-047 (hoàn thành bài)',
    'TC-COMMVP-011': 'Trùng TC-COURSE-049 (+3 điểm lesson_complete)',
    'TC-COMMVP-012': 'Trùng TC-EVENT-013 (tạo sự kiện)',
    'TC-COMMVP-013': 'Trùng TC-EVENT-050/051 (RSVP/hủy)',
    'TC-COMMVP-014': 'Trùng TC-EVENT-053/054 (đủ sức chứa 409)',
    'TC-COMMVP-015': 'Trùng TC-EVENT-058 (sự kiện đã qua 400)',
    'TC-COMMVP-016': 'Trùng TC-MEMBER-016 (tìm thành viên theo tên)',
    'TC-COMMVP-017': 'Trùng TC-MEMBER-021/032 (online 5 phút)',
    'TC-COMMVP-018': 'Trùng TC-MEMBER-038..040 (bảng xếp hạng 7/30/all)',
    'TC-COMMVP-019': 'Trùng TC-MEMBER-056 (giá trị điểm); lưu ý RSVP chỉ +1 một lần (points-policy)',
    'TC-COMMVP-020': 'Trùng TC-PAY-027 (checkout)',
    'TC-COMMVP-021': 'Trùng TC-PAY-035 (checkout khóa miễn phí 400)',
    'TC-COMMVP-023': 'Trùng TC-PAY-043 (confirm cấp quyền)',
    'TC-COMMVP-024': 'Trùng TC-PAY-044 (confirm idempotent)',
    'TC-COMMVP-025': 'Trùng TC-PAY-038 (đã tham gia checkout lại 409)',
    'TC-COURSE-001': "Kỳ vọng lỗi thời: trang chi tiết nay hiện dữ liệu thật; review/module/highlights/gains/FAQ minh họa đã gỡ (audit bước 4: community-detail.ts trả highlights=[], gains=[], faqs=[], reviews chỉ review thật; tab FAQ chỉ hiện khi có dữ liệu). Thay bằng case 'Trang chi tiết cộng đồng hiển thị dữ liệu thật...' cuối module",
    'TC-COURSE-005': "Kỳ vọng sai với thiết kế: nút 'Đã tham gia' là TOGGLE rời cộng đồng (POST /enroll), không phải 'idempotent join' (Playwright đã ghi LƯU Ý THIẾT KẾ); cộng đồng có phí còn có hộp xác nhận rời. Thay bằng case 'Bấm lại nút Đã tham gia là rời cộng đồng...' cuối module",
    'TC-COURSE-006': 'Trùng TC-COURSE-067 (mod tạo module)',
    'TC-COURSE-007': 'Trùng TC-COURSE-079/040 (thêm bài học video, embed)',
    'TC-COURSE-008': 'Trùng TC-COURSE-079/081 (bài văn bản/tệp đính kèm)',
    'TC-COURSE-009': 'Trùng TC-COURSE-077/085 (sắp xếp module/bài)',
    'TC-COURSE-010': 'Trùng TC-COURSE-047 (hoàn thành bài)',
    'TC-COURSE-011': 'Trùng TC-COURSE-024/047 (% tiến độ)',
    'TC-COURSE-012': 'Trùng TC-COURSE-097 và TC-COMMVP-022 (người chưa tham gia/chưa trả phí bị 403)',
    'TC-COURSE-013': 'Trùng TC-COURSE-097/087 (kiểm quyền ở server)',
    'TC-COURSE-014': 'Trùng TC-COURSE-040 (embed YouTube)',
    'TC-COURSE-015': 'Trùng TC-COURSE-041 (embed Vimeo trong matrix link)',
    'TC-COURSE-019': 'Trùng TC-COURSE-064 (mod/owner không bao giờ bị khóa module)',
    'TC-COURSE-020': 'Trùng TC-COURSE-087/091 (member không soạn thảo được)',
    'TC-EVENT-001': 'Trùng TC-EVENT-013/027 (mod+ tạo sự kiện)',
    'TC-EVENT-002': 'Trùng TC-EVENT-020/053 (sức chứa)',
    'TC-EVENT-003': 'Trùng TC-EVENT-050/063 (RSVP)',
    'TC-EVENT-004': 'Trùng TC-EVENT-051/052 (hủy RSVP)',
    'TC-EVENT-006': 'Trùng TC-EVENT-065/076 (tải .ics)',
    'TC-EVENT-007': 'Trùng TC-EVENT-077/084 (nhắc lịch event_reminder trong app; nhắc qua email là TC-EVENT-085)',
    'TC-EVENT-008': 'Trùng TC-EVENT-038 (sửa sự kiện)',
    'TC-EVENT-009': "Trùng TC-EVENT-047 (xóa sự kiện: người RSVP nhận thông báo 'Sự kiện đã bị hủy'; không có trạng thái 'Đã hủy')",
    'TC-EVENT-010': 'Trùng TC-EVENT-058 (sự kiện đã qua)',
    'TC-EVENT-011': 'Trùng TC-EVENT-089 (múi giờ người xem)',
    'TC-EVENT-012': 'Trùng TC-EVENT-053/054/064 (đủ chỗ: 409, không có danh sách chờ)',
    'TC-FEED-001': 'Trùng TC-FEED-019 (đăng bài chữ)',
    'TC-FEED-002': 'Trùng TC-FEED-020/031 (đăng bài kèm ảnh)',
    'TC-FEED-004': 'Trùng TC-FEED-020/027/121 (category)',
    'TC-FEED-005': 'Trùng TC-FEED-083 (bình luận)',
    'TC-FEED-006': 'Trùng TC-FEED-087/088 (trả lời lồng - hiện chưa hỗ trợ parentId, PostComment không có cột parent)',
    'TC-FEED-007': 'Trùng TC-FEED-095 (like lần đầu)',
    'TC-FEED-008': 'Trùng TC-FEED-096 (unlike/like lại)',
    'TC-FEED-009': 'Trùng TC-FEED-077 (mod ghim; quyền là mod+ chứ không riêng Owner/Admin)',
    'TC-FEED-010': 'Trùng TC-FEED-077 (ghim là toggle)',
    'TC-FEED-012': 'Trùng TC-FEED-055 (sửa bài, editedAt)',
    'TC-FEED-013': 'Trùng TC-FEED-064 (xóa bài của mình)',
    'TC-FEED-014': 'Trùng TC-FEED-058/065 (sửa/xóa bài người khác 403)',
    'TC-FEED-015': 'Trùng TC-FEED-024 (giới hạn 4000 ký tự)',
    'TC-FEED-016': 'Trùng TC-FEED-108 (báo cáo bình luận)',
    'TC-FEED-017': 'Trùng TC-FEED-090 (xóa bình luận của mình)',
    'TC-FEED-018': 'Trùng TC-FEED-078/081 (member không ghim được)',
    'TC-HOME-008': "Danh mục là tab chọn MỘT (CategoryTabs.active: CategoryId|undefined, frontend/src/features/courses/components/CategoryTabs.tsx) - không chọn nhiều danh mục cùng lúc; thay bằng case 'Chọn lần lượt các danh mục...' cuối module",
    'TC-HOME-022': "Khối 'Câu chuyện cộng đồng/Stories' đã bị gỡ khỏi trang chủ (audit bước 4; pages/HomePage.tsx chỉ còn Hero/CategoryTabs/FilterBar/CommunityCta)",
    'TC-HOME-026': 'UI không có ô nhập khoảng giá min/max (FILTER_DROPDOWNS.pricing chỉ có free/paid/trial - features/courses/constants.ts); Playwright đã skip. Bộ lọc giá hợp lệ nằm ở TC-HOME-009',
    'TC-HOME-027': 'UI không có ô nhập giá (xem TC-HOME-026); Playwright đã skip',
    'TC-HOME-028': "Phân trang là state cục bộ (useCourseFilters dùng useState, không đồng bộ URL) nên không có '?page=999' trên FE; thay bằng case nút 'Trang sau' ở trang cuối + case API tham số page cuối module (catalog.schema.ts: page min 1, max MAX_PAGE=1000)",
    'TC-HOME-029': "Như TC-HOME-028: không có ?page=0/-1 trên FE; thay bằng case nút 'Trang trước' ở trang 1 + case API tham số page",
    'TC-INTEG-001': 'Trùng TC-INTEG-014 + TC-EVENT-055/056 (race chỗ cuối)',
    'TC-INTEG-003': 'Trùng TC-PAY-126 (webhook đến trước redirect)',
    'TC-INTEG-004': 'Trùng TC-INTEG-032 + TC-PAY-127 (retry webhook idempotent)',
    'TC-INTEG-005': "Trùng TC-MONEY-109/110 (charge xong settle lỗi: reconcileUnsettledCharges) - tính năng đã làm nên không còn là 'Kế hoạch'",
    'TC-INTEG-009': 'Trùng TC-INTEG-039 + TC-NOTI-084 (SSE tự kết nối lại)',
    'TC-INTEG-010': 'Trùng TC-FEED-131 (phân trang cursor không trùng/sót)',
    'TC-INTEG-011': 'Trùng TC-INTEG-030 + TC-SEC-026 (refresh song song chỉ 1 thắng)',
    'TC-INTEG-012': 'Trùng TC-PERF-090 (50 người dùng đồng thời) và TC-PERF-055 (ngưỡng thời gian)',
    'TC-MEMBER-001': 'Trùng TC-MEMBER-016 (tìm theo tên)',
    'TC-MEMBER-002': 'Trùng TC-MEMBER-020 (lọc theo vai trò admin)',
    'TC-MEMBER-003': 'Trùng TC-MEMBER-056 + TC-FEED-019 (+5 điểm đăng bài)',
    'TC-MEMBER-004': 'Trùng TC-FEED-095/TC-MEMBER-056 (+2 điểm nhận like; chỉ BÀI VIẾT, bình luận không có like/điểm)',
    'TC-MEMBER-005': 'Trùng TC-COURSE-049 (+3 điểm hoàn thành bài)',
    'TC-MEMBER-006': 'Trùng TC-MEMBER-038',
    'TC-MEMBER-007': 'Trùng TC-MEMBER-039',
    'TC-MEMBER-008': 'Trùng TC-MEMBER-040',
    'TC-MEMBER-009': 'Trùng TC-FEED-096 (điểm chỉ tính lần like đầu, unlike không trừ)',
    'TC-MEMBER-010': 'Trùng TC-MEMBER-045 (đồng điểm xếp theo userId tăng dần)',
    'TC-MEMBER-011': 'Trùng TC-MEMBER-025/043 (người bị cấm không hiện trong danh sách/xếp hạng)',
    'TC-MEMBER-012': 'Trùng TC-MEMBER-033..037 (hồ sơ công khai)',
    'TC-NOTI-001': 'Trùng TC-FEED-083 (bình luận -> post_commented)',
    'TC-NOTI-002': 'Trùng TC-FEED-095 (like -> post_liked)',
    'TC-NOTI-004': 'Trùng TC-NOTI-101/154 (gửi tin 1-1, nút chat ở tab Thành viên)',
    'TC-NOTI-005': 'Trùng TC-NOTI-146 (realtime SSE tin nhắn)',
    'TC-NOTI-007': 'Trùng TC-PAY-125 (email hóa đơn - cùng tính năng chưa làm)',
    'TC-NOTI-008': 'Trùng TC-PAY-085 (nhắc trước gia hạn - cùng tính năng chưa làm)',
    'TC-NOTI-009': 'Trùng TC-NOTI-027/057 (đánh dấu đã đọc)',
    'TC-NOTI-010': 'Trùng TC-NOTI-032/058 (đọc tất cả)',
    'TC-NOTI-011': 'Trùng TC-NOTI-093 (không chung cộng đồng 403)',
    'TC-PAY-001': 'Trùng TC-PAY-141/222 (cổng thật - cùng tính năng chưa làm)',
    'TC-PAY-002': 'Trùng TC-PAY-141/222 (Stripe thật)',
    'TC-PAY-003': "Trùng TC-PAY-050 (cổng từ chối thẻ: 402 PAYMENT_FAILED); lý do cụ thể 'thẻ hết hạn' chỉ có với cổng thật (TC-PAY-141)",
    'TC-PAY-004': "Trùng TC-PAY-050 (cổng từ chối); lý do 'không đủ số dư' chỉ có với cổng thật",
    'TC-PAY-005': 'Trùng TC-PAY-083/084 (gia hạn thất bại hiện hết hạn ngay, dunning chưa làm)',
    'TC-PAY-006': 'Trùng TC-PAY-083/084 (cùng chính sách dunning chưa làm)',
    'TC-PAY-007': 'Trùng TC-PAY-058 (dùng thử 7 ngày)',
    'TC-PAY-008': 'Trùng TC-PAY-078 (hủy trong dùng thử)',
    'TC-PAY-009': 'Trùng TC-PAY-073 (hủy cuối kỳ vẫn còn quyền)',
    'TC-PAY-010': 'Trùng TC-PAY-081 (scheduler gia hạn)',
    'TC-PAY-011': 'Trùng TC-PAY-085 (nhắc trước gia hạn)',
    'TC-PAY-012': 'Trùng TC-PAY-122/142 (Gói của tôi)',
    'TC-PAY-014': 'Trùng TC-PAY-161 (dashboard doanh thu)',
    'TC-PAY-015': 'Trùng TC-PAY-167 (rút tiền hợp lệ)',
    'TC-PAY-016': 'Trùng TC-PAY-169 (dưới ngưỡng $50)',
    'TC-PAY-017': 'Trùng TC-PAY-127 (webhook trùng event id)',
    'TC-PAY-018': 'Trùng TC-PAY-129 (webhook chữ ký sai)',
    'TC-PAY-020': 'Trùng TC-PAY-088 (hoàn tiền tự duyệt) và TC-PAY-100 (admin duyệt)',
    'TC-PAY-021': 'Trùng TC-PAY-165 (hiển thị USD) và TC-PAY-166 (đa tiền tệ - chưa làm)',
    'TC-PAY-022': 'Trùng TC-PAY-148 (nhiều gói độc lập)',
    'TC-PAY-023': 'Trùng TC-PAY-056 (double submit)',
    'TC-PAY-024': 'Trùng TC-PAY-060 (không dùng thử lần 2)',
    'TC-PAY-025': 'Trùng TC-PAY-207 (Owner cộng đồng khác 403)',
    'TC-PAY-026': 'Trùng TC-PAY-170 (vượt số dư khả dụng 400)',
    'TC-ROLE-001': 'Trùng TC-ROLE-053/093 (khách bị 401/chuyển đăng nhập)',
    'TC-ROLE-002': 'Trùng TC-ROLE-090 (trang Cài đặt cộng đồng chặn member)',
    'TC-ROLE-003': 'Trùng TC-ROLE-038 + TC-COMM-058 (admin không đổi giá)',
    'TC-ROLE-004': 'Trùng TC-ROLE-046 + TC-COMM-066 (chỉ Owner/Platform Admin xóa)',
    'TC-ROLE-005': 'Trùng TC-ROLE-057 (Owner cộng đồng A không quản trị cộng đồng B)',
    'TC-ROLE-006': 'Trùng TC-ROLE-056 (Platform Admin qua requireMembership)',
    'TC-ROLE-007': 'Trùng TC-ROLE-061 (hóa đơn/giao dịch người khác 403)',
    'TC-ROLE-009': 'Trùng TC-ROLE-063 (hội thoại người khác 404)',
    'TC-ROLE-010': 'Trùng TC-COURSE-087 và các case ma trận TC-ROLE-032..046 (member gọi API quản trị bị 403)',
    'TC-ROLE-011': 'Trùng TC-ROLE-082/083 + TC-SEC-020/023 (sửa claim role, quyền lấy từ DB)',
    'TC-ROLE-012': 'Trùng TC-ROLE-086 (CSRF: API dùng Bearer, không dựa cookie)',
    'TC-ROLE-013': 'Trùng TC-SEARCH-019 (40 req/phút), TC-GAME-066..069 (nhóm ghi) và TC-SEC-055/056 (đăng nhập/quên mật khẩu)',
    'TC-ROLE-014': 'Trùng TC-UPLOAD-012/015 (chặn .exe/.php, magic bytes)',
    'TC-ROLE-015': 'Trùng TC-UPLOAD-024 (413 vượt dung lượng)',
    'TC-ROLE-016': 'Trùng TC-ROLE-089/092 (ẩn/hiện menu theo vai trò)',
    'TC-ROLE-017': 'Trùng TC-SEC-032/067 và TC-MEMBER-027/029 (không lộ trường nhạy cảm)',
    'TC-ROLE-018': 'Trùng TC-AUTH-018 (back sau đăng xuất)',
    'TC-SEC-001': 'Trùng TC-SEC-035 (bcrypt cost 10, không lưu mật khẩu thô) và TC-SEC-032/067',
    'TC-SEC-006': 'Trùng TC-ROLE-057 (vai trò theo từng cộng đồng, Owner A không có quyền ở cộng đồng khác) và TC-ROLE-058',
}
