# -*- coding: utf-8 -*-
"""Phần 4 (rà soát): payments / comms / platform. Lý do + bằng chứng, xem qa/review_notes/part4.md."""
RETIRED = {
    'TC-PAY-053': "Hành vi đổi có chủ đích: checkout nay TÁI DÙNG intent pending <30 phút của cùng (user, cộng đồng) kể cả Idempotency-Key khác (payments.service.ts checkout/findReusablePending; payments.md 3.1). Đã có MONEY 'Checkout lần 2 khi còn intent pending tái dùng...'.",
    'TC-PAY-110': 'UI /admin 4 tab (Hoàn tiền/Rút tiền/Báo cáo/Khóa) đã bị thay bằng Admin Console (frontend/src/App.tsx /admin/* -> AdminRoutes); trùng ADM2 mục Thanh toán > Hoàn tiền.',
    'TC-PAY-199': 'UI tab Rút tiền ở /admin cũ đã bỏ (Admin Console thay thế); trùng ADM2 mục Chi trả. API đã có PAY-192..198.',
    'TC-PAY-200': "Kỳ vọng lỗi thời: nay hoàn tiền sau payout ghi sổ nợ OwnerBalanceLedger và chặn payout PAYOUT_BLOCKED (payments.md 3.5); trùng MONEY 'Kịch bản nợ S1/S2'.",
    'TC-PAY-214': "Kỳ vọng sai: kick nay kết thúc gói NGAY + thông báo 'không bị tính phí thêm' (endMembership, payments.md 3.2); MONEY đã có case kick.",
    'TC-PAY-215': 'Kỳ vọng sai: ban nay dừng gia hạn (cancelAtPeriodEnd) + gỡ quyền, gỡ ban trả quyền (stopRenewals, payments.md 3.2/3.3); MONEY/GAME đã có.',
    'TC-PAY-217': 'Đã làm: xóa cộng đồng gọi endAllForCommunity kết thúc gói, scheduler không thu phí (payments.md 3.2); MONEY đã có case xóa/khóa cộng đồng.',
    'TC-NOTI-068': 'Đã chốt trong code: ?access_token= bị bỏ, chỉ Bearer/ticket (notifications.routes.ts streamAuth, notifications.md); SECX có case SSE. Phần còn mở (cookie vs ticket) không phải test case.',
    'TC-NOTI-074': "Tính năng bị gỡ: ?access_token= nay luôn 401 (notifications.routes.ts:25-33, notifications.md 'Đã bỏ'); SECX nhóm SSE đã kiểm.",
    'TC-NOTI-151': "Cơ chế online-signal (push()===0) đã gỡ: luôn lưu thông báo, chỉ bỏ khi chính người nhận vừa xem cuộc trò chuyện <30s (messages.md 'Thông báo'); INFRA mục 5 đã có 'SSE mở nhưng không xem vẫn có Notification' và 'đang xem ack 30s'.",
    'TC-SEARCH-007': "Ngữ nghĩa cũ (chỉ khớp chuỗi con nguyên cụm) đã đổi: nay khớp theo từ, tiền tố từng từ, không cần đúng thứ tự (search.md 'Cách hoạt động'); PERF-007/012 đã có.",
    'TC-SEARCH-028': "Ghi chú 'Post chưa có hidden' sai; hidden đã lọc trong SQL, tác giả thường KHÔNG tự thấy bài ẩn của mình (search.md Quy tắc hiển thị); trùng PERF-030.",
    'TC-SEARCH-046': 'Đã làm: tsvector/GIN, ts_rank, pg_trgm chịu gõ sai (search.md; migration 20261005100000); PERF-012/014/022/023 đã phủ.',
    'TC-SEARCH-048': 'Đã đẩy xuống SQL, hết trần 1000 mục; trùng PERF-024 (bài cũ vẫn tìm được) và PERF-047.',
    'TC-UPLOAD-045': 'Kỳ vọng ngược chiều đã chốt: message_attachment là file riêng tư, ẩn danh nhận 401, cần Bearer/URL ký (uploads.routes.ts GET /files/:key; uploads.md). SECX có ma trận /files theo purpose.',
    'TC-ADMIN-055': "UI /admin 4 tab ('Quản trị nền tảng') đã được thay bằng Admin Console (App.tsx /admin/*); trùng ADM (khung admin).",
    'TC-ADMIN-057': 'FE không còn xác định admin bằng GET /admin/refunds mà bằng GET /admin/me (frontend/src/features/admin/queries.ts:10); ADM đã có case /admin/me.',
    'TC-ADMIN-063': "Tab 'Khóa cộng đồng' của /admin cũ đã bỏ; khóa/mở khóa nay trong Admin Console (ADM Cộng đồng). API lock vẫn được ADMIN-058..062 phủ.",
    'TC-ADMIN-074': 'Đã làm: Admin Console có Dashboard tổng quan (ADM).',
    'TC-ADMIN-075': 'Đã làm: Admin Console có danh sách/tìm kiếm Người dùng và Cộng đồng (ADM).',
    'TC-ADMIN-076': 'Đã làm: admin suspend/ban tài khoản toàn nền tảng (admin-users.service.ts suspend/ban; ADM Người dùng).',
    'TC-INTEG-018': 'Trùng PAY-057 (confirm song song) và MONEY.',
    'TC-INTEG-019': 'Trùng PAY-052 (Idempotency-Key cùng key).',
    'TC-INTEG-020': 'Trùng PAY-054.',
    'TC-INTEG-023': 'Trùng PAY-191 (rút tiền song song, đã cập nhật theo số có thể rút).',
    'TC-INTEG-024': "Trùng MONEY 'hai request PATCH approve cùng lúc' và PAY-097/102.",
    'TC-INTEG-031': 'Trùng PAY-126 (webhook payment.succeeded).',
    'TC-INTEG-032': 'Trùng PAY-127 (webhook trùng event id); ngữ nghĩa duplicate mới (done/processing) thuộc MONEY.',
    'TC-INTEG-033': 'Trùng PAY-128..133.',
    'TC-INTEG-034': 'Trùng PAY-130 (sửa body sau khi ký).',
    'TC-INTEG-035': 'Trùng PAY-135 (ignored).',
    'TC-INTEG-036': "Kỳ vọng sai: webhook payment.refunded nay áp dụng ngay (RefundRequest auto, status approved, cổng không gọi lại) - payments.service.ts case 'payment.refunded'; PAY-137 đã đúng.",
    'TC-INTEG-037': 'Trùng NOTI-069..073 (vé SSE).',
    'TC-INTEG-038': 'Trùng NOTI-076 (SSE realtime).',
    'TC-INTEG-040': 'Trùng NOTI-147/080 (SSE tin nhắn nhiều tab).',
    'TC-INTEG-041': '?access_token= đã bỏ (luôn 401); xem NOTI-074, SECX.',
    'TC-INTEG-049': 'Trùng SECX: /api/dev/outbox nay chỉ mount khi ENABLE_DEV_OUTBOX=1, không còn theo NODE_ENV (cases_audit_secx.py dòng 69-77).',
    'TC-INTEG-050': 'Trùng SECX (guard secret dev-* khi production, env-guard.ts).',
    'TC-SEC-057': 'Lỗi thời: nay có rate limit toàn cục 1200/phút/IP + nhóm ghi (middlewares/rate-limit.ts); GAME đã có case rate limit.',
}
