# -*- coding: utf-8 -*-
"""Phan 5: ra soat ADM/ADM2/ADM3/SECX/MONEY/GAME/INFRA/PERF/SPLIT (xem qa/review_notes/part5.md)."""
RETIRED = {
    'TC-ADM-012': 'Trùng UI: chặn non-staff dùng cùng guard AdminLayout.tsx:387 như TC-ADM-011; phần API owner/cadmin đã có TC-ADM-004/005',
    'TC-ADM-013': 'Trùng UI: chặn non-staff dùng cùng guard AdminLayout.tsx:387 như TC-ADM-011; phần API owner/cadmin đã có TC-ADM-004/005',
    'TC-ADM-025': "Lỗi thời: mục 'Sắp có' đã xóa (docs/features/admin-batch3.md 'Không còn Sắp có'; AdminRoutes không còn ComingSoon); TC-ADM2-001/TC-ADM3-019 đã kiểm tra",
    'TC-ADM-026': "Lỗi thời: mục 'Sắp có' đã xóa (docs/features/admin-batch3.md 'Không còn Sắp có'; AdminRoutes không còn ComingSoon); TC-ADM2-001/TC-ADM3-019 đã kiểm tra",
    'TC-ADM-027': "Lỗi thời: mục 'Sắp có' đã xóa (docs/features/admin-batch3.md 'Không còn Sắp có'; AdminRoutes không còn ComingSoon); TC-ADM2-001/TC-ADM3-019 đã kiểm tra",
    'TC-ADM-028': "Lỗi thời: mục 'Sắp có' đã xóa (docs/features/admin-batch3.md 'Không còn Sắp có'; AdminRoutes không còn ComingSoon); TC-ADM2-001/TC-ADM3-019 đã kiểm tra",
    'TC-ADM-029': "Lỗi thời: mục 'Sắp có' đã xóa (docs/features/admin-batch3.md 'Không còn Sắp có'; AdminRoutes không còn ComingSoon); TC-ADM2-001/TC-ADM3-019 đã kiểm tra",
    'TC-ADM-030': "Lỗi thời: mục 'Sắp có' đã xóa (docs/features/admin-batch3.md 'Không còn Sắp có'; AdminRoutes không còn ComingSoon); TC-ADM2-001/TC-ADM3-019 đã kiểm tra",
    'TC-ADM-138': 'Lỗi thời: xóa/đình chỉ cộng đồng nay kết thúc/ngừng gia hạn gói (admin-communities.service.ts:413,440 endAllForCommunity; TC-MONEY-019/022)',
    'TC-ADM-249': 'Thay bởi TC-ADM3-350: trang audit nay có cột vai trò/IP/Vụ việc, seed >11 dòng sau đợt 2/3',
    'TC-ADM-250': 'Trùng TC-ADM3-351/352 (bộ lọc Quản trị viên/Nhóm/Hành động/ngày + tìm kiếm)',
    'TC-ADM-251': 'Trùng TC-ADM3-357 (API audit-logs lọc actor/action/tiền tố/targetType/targetId/q/from/to)',
    'TC-ADM-252': 'Trùng TC-ADM3-357 (API audit-logs lọc actor/action/tiền tố/targetType/targetId/q/from/to)',
    'TC-ADM-261': 'Trùng TC-ADM3-394 (hiệu năng audit/support/admin < 1s)',
    'TC-ADM-262': "Trùng TC-ADM2-175..188 và TC-ADM2-221/226 (hoàn tiền/chi trả trong khung admin); dùng id seed cũ 'demo-paid-demo-2/seed-pay-pendref'",
    'TC-ADM-263': "Trùng TC-ADM2-175..188 và TC-ADM2-221/226 (hoàn tiền/chi trả trong khung admin); dùng id seed cũ 'demo-paid-demo-2/seed-pay-pendref'",
    'TC-ADM-264': "Trùng TC-ADM2-175..188 và TC-ADM2-221/226 (hoàn tiền/chi trả trong khung admin); dùng id seed cũ 'demo-paid-demo-2/seed-pay-pendref'",
    'TC-ADM-265': "Trùng TC-ADM2-175..188 và TC-ADM2-221/226 (hoàn tiền/chi trả trong khung admin); dùng id seed cũ 'demo-paid-demo-2/seed-pay-pendref'",
    'TC-ADM-266': 'Trùng TC-ADM-011 và TC-ADM2-020 (member bị chặn trang admin)',
    'TC-ADM-268': "Trùng TC-ADM-015 (/admin/reports chuyển hướng); 'AdminPage cũ không còn' là chi tiết cài đặt, không phải hành vi kiểm thử",
    'TC-ADM-277': 'Đã làm: TC-MONEY-019/021/022 phủ (admin-communities.service.ts:413,440; communities.service.ts:145,159)',
    'TC-ADM-278': 'Đã làm: vai trò Moderator/Support/Finance + quyền theo route (admin-staff.permissions.ts); phủ bởi ADM3 ma trận quyền',
    'TC-ADM-279': 'Trùng TC-ADM3-395/396 (2FA/require2fa chưa thật)',
    'TC-ADM-287': 'Đã làm: AuditView có bộ lọc Quản trị viên/Hành động/ngày (TC-ADM3-351)',
    'TC-ADM-290': 'Đã làm: nhóm Nội dung/Thanh toán/Khám phá/Phân tích/Hỗ trợ/Hệ thống đã có (admin-batch2/3.md, nav.ts)',
    'TC-ADM2-003': "Trùng: smoke 'mở trực tiếp trang' lặp 16 lần cùng cơ chế lazy route (AdminRoutes.tsx); giữ TC-ADM2-002 đại diện, từng trang đã có case riêng",
    'TC-ADM2-004': "Trùng: smoke 'mở trực tiếp trang' lặp 16 lần cùng cơ chế lazy route (AdminRoutes.tsx); giữ TC-ADM2-002 đại diện, từng trang đã có case riêng",
    'TC-ADM2-005': "Trùng: smoke 'mở trực tiếp trang' lặp 16 lần cùng cơ chế lazy route (AdminRoutes.tsx); giữ TC-ADM2-002 đại diện, từng trang đã có case riêng",
    'TC-ADM2-006': "Trùng: smoke 'mở trực tiếp trang' lặp 16 lần cùng cơ chế lazy route (AdminRoutes.tsx); giữ TC-ADM2-002 đại diện, từng trang đã có case riêng",
    'TC-ADM2-007': "Trùng: smoke 'mở trực tiếp trang' lặp 16 lần cùng cơ chế lazy route (AdminRoutes.tsx); giữ TC-ADM2-002 đại diện, từng trang đã có case riêng",
    'TC-ADM2-008': "Trùng: smoke 'mở trực tiếp trang' lặp 16 lần cùng cơ chế lazy route (AdminRoutes.tsx); giữ TC-ADM2-002 đại diện, từng trang đã có case riêng",
    'TC-ADM2-009': "Trùng: smoke 'mở trực tiếp trang' lặp 16 lần cùng cơ chế lazy route (AdminRoutes.tsx); giữ TC-ADM2-002 đại diện, từng trang đã có case riêng",
    'TC-ADM2-010': "Trùng: smoke 'mở trực tiếp trang' lặp 16 lần cùng cơ chế lazy route (AdminRoutes.tsx); giữ TC-ADM2-002 đại diện, từng trang đã có case riêng",
    'TC-ADM2-011': "Trùng: smoke 'mở trực tiếp trang' lặp 16 lần cùng cơ chế lazy route (AdminRoutes.tsx); giữ TC-ADM2-002 đại diện, từng trang đã có case riêng",
    'TC-ADM2-012': "Trùng: smoke 'mở trực tiếp trang' lặp 16 lần cùng cơ chế lazy route (AdminRoutes.tsx); giữ TC-ADM2-002 đại diện, từng trang đã có case riêng",
    'TC-ADM2-013': "Trùng: smoke 'mở trực tiếp trang' lặp 16 lần cùng cơ chế lazy route (AdminRoutes.tsx); giữ TC-ADM2-002 đại diện, từng trang đã có case riêng",
    'TC-ADM2-014': "Trùng: smoke 'mở trực tiếp trang' lặp 16 lần cùng cơ chế lazy route (AdminRoutes.tsx); giữ TC-ADM2-002 đại diện, từng trang đã có case riêng",
    'TC-ADM2-015': "Trùng: smoke 'mở trực tiếp trang' lặp 16 lần cùng cơ chế lazy route (AdminRoutes.tsx); giữ TC-ADM2-002 đại diện, từng trang đã có case riêng",
    'TC-ADM2-016': "Trùng: smoke 'mở trực tiếp trang' lặp 16 lần cùng cơ chế lazy route (AdminRoutes.tsx); giữ TC-ADM2-002 đại diện, từng trang đã có case riêng",
    'TC-ADM2-017': "Trùng: smoke 'mở trực tiếp trang' lặp 16 lần cùng cơ chế lazy route (AdminRoutes.tsx); giữ TC-ADM2-002 đại diện, từng trang đã có case riêng",
    'TC-ADM2-018': "Trùng: smoke 'mở trực tiếp trang' lặp 16 lần cùng cơ chế lazy route (AdminRoutes.tsx); giữ TC-ADM2-002 đại diện, từng trang đã có case riêng",
    'TC-ADM2-021': 'Trùng UI guard: cùng đường chặn non-staff như TC-ADM2-020 / TC-ADM-011 (AdminLayout.tsx:387)',
    'TC-ADM2-022': 'Trùng UI guard: cùng đường chặn non-staff như TC-ADM2-020 / TC-ADM-011 (AdminLayout.tsx:387)',
    'TC-ADM2-023': 'Trùng UI guard: cùng đường chặn non-staff như TC-ADM2-020 / TC-ADM-011 (AdminLayout.tsx:387)',
    'TC-ADM2-025': 'Trùng TC-ADM2-024 (46 route 401/403) và ma trận TC-ADM3-054..094',
    'TC-ADM2-083': "Lỗi thời: 'mô-đun' (ClassroomModule) nay là Khóa học (Course) - admin-content.service.ts:207; /courses/:id/modules chỉ là khóa mặc định (communities-courses.md mục 0.4); thay bởi TC-SPLIT-044/053/061/096",
    'TC-ADM2-084': 'Lỗi thời: Khóa học admin không còn là ClassroomModule; thumbnail = thumbnailUrl (admin-content.service.ts:248); thay bởi TC-SPLIT-094',
    'TC-ADM2-119': 'Trùng: trạng thái tải/lỗi dùng chung DataTable, đã có TC-ADM2-038',
    'TC-ADM2-124': 'Thay bởi TC-SECX-094: nút Xem trước Media nay mở qua URL ký (POST /files/:key/url)',
    'TC-ADM2-140': 'Trùng: trạng thái rỗng/tải/lỗi dùng chung DataTable, đã có TC-ADM2-038',
    'TC-ADM2-158': 'Trùng TC-MONEY-059 (hoàn tiền giao dịch kỳ hiện tại hủy gói + thu hồi quyền)',
    'TC-ADM2-190': 'Trùng TC-MONEY-050/056/151 (cửa sổ hoàn tiền 7 ngày tự duyệt/chờ admin, biên)',
    'TC-ADM2-249': 'Trùng: trạng thái tải/lỗi/rỗng DataTable, đã có TC-ADM2-038',
    'TC-ADM2-305': 'Lỗi thời: nhãn audit đã Việt hóa bằng auditLabel (frontend/src/features/admin/types.batch3.ts:449, Batch2Parts.tsx:365); phần còn mã thô: TC-ADM3-354',
    'TC-ADM2-311': 'Trùng TC-ADM2-310: cùng pageQuery dùng chung (admin-b2.common.ts)',
    'TC-ADM2-312': 'Trùng TC-ADM2-310: cùng pageQuery dùng chung (admin-b2.common.ts)',
    'TC-ADM2-326': "Lỗi thời: trạng thái 'Đang hoàn tiền' (refunding) đã có (PaymentsViews.tsx:464); xem TC-MONEY-064/065",
    'TC-ADM2-336': 'Trùng TC-ADM3-418; các giá trị tạm nay chỉnh được ở Cài đặt chung',
    'TC-ADM2-337': 'Đã làm: kick/ban/xóa/khóa kết thúc gói (TC-MONEY-017/018/019/021/022)',
    'TC-ADM3-007': 'Trùng TC-ADM3-006 (cùng GuardedOutlet AdminLayout.tsx:313 + requiredPerm); từng vai trò đã có case sidebar 002..005',
    'TC-ADM3-008': 'Trùng TC-ADM3-006 (cùng GuardedOutlet AdminLayout.tsx:313 + requiredPerm); từng vai trò đã có case sidebar 002..005',
    'TC-ADM3-009': 'Trùng TC-ADM3-006 (cùng GuardedOutlet AdminLayout.tsx:313 + requiredPerm); từng vai trò đã có case sidebar 002..005',
    'TC-ADM3-021': "Trùng: smoke 'mở trực tiếp trang' lặp 18 lần cùng cơ chế lazy route; giữ TC-ADM3-020 đại diện, mỗi trang có case riêng",
    'TC-ADM3-022': "Trùng: smoke 'mở trực tiếp trang' lặp 18 lần cùng cơ chế lazy route; giữ TC-ADM3-020 đại diện, mỗi trang có case riêng",
    'TC-ADM3-023': "Trùng: smoke 'mở trực tiếp trang' lặp 18 lần cùng cơ chế lazy route; giữ TC-ADM3-020 đại diện, mỗi trang có case riêng",
    'TC-ADM3-024': "Trùng: smoke 'mở trực tiếp trang' lặp 18 lần cùng cơ chế lazy route; giữ TC-ADM3-020 đại diện, mỗi trang có case riêng",
    'TC-ADM3-025': "Trùng: smoke 'mở trực tiếp trang' lặp 18 lần cùng cơ chế lazy route; giữ TC-ADM3-020 đại diện, mỗi trang có case riêng",
    'TC-ADM3-026': "Trùng: smoke 'mở trực tiếp trang' lặp 18 lần cùng cơ chế lazy route; giữ TC-ADM3-020 đại diện, mỗi trang có case riêng",
    'TC-ADM3-027': "Trùng: smoke 'mở trực tiếp trang' lặp 18 lần cùng cơ chế lazy route; giữ TC-ADM3-020 đại diện, mỗi trang có case riêng",
    'TC-ADM3-028': "Trùng: smoke 'mở trực tiếp trang' lặp 18 lần cùng cơ chế lazy route; giữ TC-ADM3-020 đại diện, mỗi trang có case riêng",
    'TC-ADM3-029': "Trùng: smoke 'mở trực tiếp trang' lặp 18 lần cùng cơ chế lazy route; giữ TC-ADM3-020 đại diện, mỗi trang có case riêng",
    'TC-ADM3-030': "Trùng: smoke 'mở trực tiếp trang' lặp 18 lần cùng cơ chế lazy route; giữ TC-ADM3-020 đại diện, mỗi trang có case riêng",
    'TC-ADM3-031': "Trùng: smoke 'mở trực tiếp trang' lặp 18 lần cùng cơ chế lazy route; giữ TC-ADM3-020 đại diện, mỗi trang có case riêng",
    'TC-ADM3-032': "Trùng: smoke 'mở trực tiếp trang' lặp 18 lần cùng cơ chế lazy route; giữ TC-ADM3-020 đại diện, mỗi trang có case riêng",
    'TC-ADM3-033': "Trùng: smoke 'mở trực tiếp trang' lặp 18 lần cùng cơ chế lazy route; giữ TC-ADM3-020 đại diện, mỗi trang có case riêng",
    'TC-ADM3-034': "Trùng: smoke 'mở trực tiếp trang' lặp 18 lần cùng cơ chế lazy route; giữ TC-ADM3-020 đại diện, mỗi trang có case riêng",
    'TC-ADM3-035': "Trùng: smoke 'mở trực tiếp trang' lặp 18 lần cùng cơ chế lazy route; giữ TC-ADM3-020 đại diện, mỗi trang có case riêng",
    'TC-ADM3-036': "Trùng: smoke 'mở trực tiếp trang' lặp 18 lần cùng cơ chế lazy route; giữ TC-ADM3-020 đại diện, mỗi trang có case riêng",
    'TC-ADM3-037': "Trùng: smoke 'mở trực tiếp trang' lặp 18 lần cùng cơ chế lazy route; giữ TC-ADM3-020 đại diện, mỗi trang có case riêng",
    'TC-ADM3-038': "Trùng: smoke 'mở trực tiếp trang' lặp 18 lần cùng cơ chế lazy route; giữ TC-ADM3-020 đại diện, mỗi trang có case riêng",
    'TC-ADM3-039': 'Trùng ma trận: chiều role x đợt lặp lại thông tin của 41 case theo route TC-ADM3-054..094 (cùng bảng PERMS/admin-staff.permissions.ts)',
    'TC-ADM3-040': 'Trùng ma trận: chiều role x đợt lặp lại thông tin của 41 case theo route TC-ADM3-054..094 (cùng bảng PERMS/admin-staff.permissions.ts)',
    'TC-ADM3-041': 'Trùng ma trận: chiều role x đợt lặp lại thông tin của 41 case theo route TC-ADM3-054..094 (cùng bảng PERMS/admin-staff.permissions.ts)',
    'TC-ADM3-042': 'Trùng ma trận: chiều role x đợt lặp lại thông tin của 41 case theo route TC-ADM3-054..094 (cùng bảng PERMS/admin-staff.permissions.ts)',
    'TC-ADM3-043': 'Trùng ma trận: chiều role x đợt lặp lại thông tin của 41 case theo route TC-ADM3-054..094 (cùng bảng PERMS/admin-staff.permissions.ts)',
    'TC-ADM3-044': 'Trùng ma trận: chiều role x đợt lặp lại thông tin của 41 case theo route TC-ADM3-054..094 (cùng bảng PERMS/admin-staff.permissions.ts)',
    'TC-ADM3-045': 'Trùng ma trận: chiều role x đợt lặp lại thông tin của 41 case theo route TC-ADM3-054..094 (cùng bảng PERMS/admin-staff.permissions.ts)',
    'TC-ADM3-046': 'Trùng ma trận: chiều role x đợt lặp lại thông tin của 41 case theo route TC-ADM3-054..094 (cùng bảng PERMS/admin-staff.permissions.ts)',
    'TC-ADM3-047': 'Trùng ma trận: chiều role x đợt lặp lại thông tin của 41 case theo route TC-ADM3-054..094 (cùng bảng PERMS/admin-staff.permissions.ts)',
    'TC-ADM3-048': 'Trùng ma trận: chiều role x đợt lặp lại thông tin của 41 case theo route TC-ADM3-054..094 (cùng bảng PERMS/admin-staff.permissions.ts)',
    'TC-ADM3-049': 'Trùng ma trận: chiều role x đợt lặp lại thông tin của 41 case theo route TC-ADM3-054..094 (cùng bảng PERMS/admin-staff.permissions.ts)',
    'TC-ADM3-050': 'Trùng ma trận: chiều role x đợt lặp lại thông tin của 41 case theo route TC-ADM3-054..094 (cùng bảng PERMS/admin-staff.permissions.ts)',
    'TC-ADM3-051': 'Trùng ma trận: chiều role x đợt lặp lại thông tin của 41 case theo route TC-ADM3-054..094 (cùng bảng PERMS/admin-staff.permissions.ts)',
    'TC-ADM3-052': 'Trùng ma trận: chiều role x đợt lặp lại thông tin của 41 case theo route TC-ADM3-054..094 (cùng bảng PERMS/admin-staff.permissions.ts)',
    'TC-ADM3-053': 'Trùng ma trận: chiều role x đợt lặp lại thông tin của 41 case theo route TC-ADM3-054..094 (cùng bảng PERMS/admin-staff.permissions.ts)',
    'TC-ADM3-096': 'Trùng TC-ADM3-097 và 054..094 (401/403 non-staff)',
    'TC-ADM3-103': 'Trùng ma trận route (TC-ADM3-058/059/068/074); khoảng trống nút theo quyền đã nằm ở TC-ADM3-408',
    'TC-ADM3-104': 'Trùng ma trận route (TC-ADM3-058/059/068/074); khoảng trống nút theo quyền đã nằm ở TC-ADM3-408',
    'TC-ADM3-119': 'Trùng: chip 7/30/90 lặp cho 6 trang Phân tích cùng DateRangeChips; giữ TC-ADM3-115',
    'TC-ADM3-121': 'Trùng: trạng thái lỗi/tải lặp cho 6 trang Phân tích cùng khối; giữ TC-ADM3-117',
    'TC-ADM3-123': 'Trùng: chip 7/30/90 lặp cho 6 trang Phân tích cùng DateRangeChips; giữ TC-ADM3-115',
    'TC-ADM3-125': 'Trùng: trạng thái lỗi/tải lặp cho 6 trang Phân tích cùng khối; giữ TC-ADM3-117',
    'TC-ADM3-127': 'Trùng: chip 7/30/90 lặp cho 6 trang Phân tích cùng DateRangeChips; giữ TC-ADM3-115',
    'TC-ADM3-129': 'Trùng: trạng thái lỗi/tải lặp cho 6 trang Phân tích cùng khối; giữ TC-ADM3-117',
    'TC-ADM3-131': 'Trùng: chip 7/30/90 lặp cho 6 trang Phân tích cùng DateRangeChips; giữ TC-ADM3-115',
    'TC-ADM3-133': 'Trùng: trạng thái lỗi/tải lặp cho 6 trang Phân tích cùng khối; giữ TC-ADM3-117',
    'TC-ADM3-135': 'Trùng: chip 7/30/90 lặp cho 6 trang Phân tích cùng DateRangeChips; giữ TC-ADM3-115',
    'TC-ADM3-137': 'Trùng: trạng thái lỗi/tải lặp cho 6 trang Phân tích cùng khối; giữ TC-ADM3-117',
    'TC-ADM3-162': 'Trùng ma trận TC-ADM3-081/082 (analytics.view)',
    'TC-ADM3-205': 'Trùng TC-ADM3-003/004/005/007 + 083/084 (support.manage, UI guard)',
    'TC-ADM3-224': 'Trùng TC-ADM3-083/084 (support.manage)',
    'TC-ADM3-238': 'Lỗi thời: đã có trang /contact gửi POST /api/contact (App.tsx:78, frontend/src/features/support/api.ts:14); thay bằng case mới cuối module',
    'TC-ADM3-264': 'Trùng TC-ADM3-087/088 (admin.manage)',
    'TC-ADM3-283': 'Trùng TC-ADM3-085 (community.manage cho categories)',
    'TC-ADM3-298': 'Trùng TC-ADM3-086 (system.flags)',
    'TC-ADM3-309': 'Trùng TC-ADM3-089 (system.settings tích hợp)',
    'TC-ADM3-326': 'Trùng TC-ADM3-090 (system.settings thông báo)',
    'TC-ADM3-349': 'Trùng TC-ADM3-091 (system.settings mẫu email)',
    'TC-ADM3-362': 'Trùng TC-ADM3-062/093 (audit.view)',
    'TC-ADM3-378': 'Trùng TC-ADM3-092 (system.settings)',
    'TC-GAME-037': 'Kịch bản lặp lại TC-GAME-021/022/028/033 (locked: sửa/xóa/chuyển quyền/rút tiền)',
    'TC-GAME-038': 'Kịch bản lặp lại TC-GAME-021/022/028/033 (locked: sửa/xóa/chuyển quyền/rút tiền)',
    'TC-INFRA-006': 'Trùng TC-INFRA-003 (bước typecheck CI)',
    'TC-INFRA-008': 'Không phải kiểm thử sản phẩm (cố ý phá lint/build/test để thử CI) - thuộc nhóm dev',
    'TC-INFRA-010': 'Trùng TC-INFRA-003/TC-MONEY-163 (npm test xanh)',
    'TC-INFRA-011': 'Không phải kiểm thử sản phẩm (cố ý phá lint/build/test để thử CI) - thuộc nhóm dev',
    'TC-INFRA-012': 'Không phải kiểm thử sản phẩm (cố ý phá lint/build/test để thử CI) - thuộc nhóm dev',
    'TC-INFRA-046': 'Biến thể unit trùng TC-INFRA-045/TC-SECX-104',
    'TC-INFRA-050': 'Trùng TC-SECX-015 (email production log-only)',
    'TC-INFRA-070': 'Không phải kiểm thử (ghi chú vận hành gói free)',
    'TC-INFRA-093': 'Trùng TC-INFRA-009 (script coverage)',
    'TC-MONEY-020': 'Tập con của ma trận TC-MONEY-133/134/135/137 (checkout/trial/confirm khi khóa/tạm ngưng/xóa/cấm)',
    'TC-MONEY-022': 'Tập con của ma trận TC-MONEY-133/134/135/137 (checkout/trial/confirm khi khóa/tạm ngưng/xóa/cấm)',
    'TC-MONEY-031': 'Tập con của ma trận TC-MONEY-133/134/135/137 (checkout/trial/confirm khi khóa/tạm ngưng/xóa/cấm)',
    'TC-MONEY-127': 'Trùng sau cập nhật TC-ADM2-205/210/220 (UI Admin Doanh thu creator + chi tiết payout có cột Có thể rút/Đang giữ/Dự phòng/Nợ)',
    'TC-MONEY-128': 'Trùng sau cập nhật TC-ADM2-205/210/220 (UI Admin Doanh thu creator + chi tiết payout có cột Có thể rút/Đang giữ/Dự phòng/Nợ)',
    'TC-MONEY-129': 'Trùng sau cập nhật TC-ADM2-205/210/220 (UI Admin Doanh thu creator + chi tiết payout có cột Có thể rút/Đang giữ/Dự phòng/Nợ)',
    'TC-MONEY-130': 'Trùng TC-ADM2-232 và TC-ADM3-079/080 (route cũ /admin/payouts)',
    'TC-MONEY-132': 'Trùng TC-ADM3-418 (giá trị nghiệp vụ tạm)',
    'TC-MONEY-146': 'Trùng TC-ADM-260/TC-ADM2-188 (audit hoàn tiền/chi trả)',
    'TC-MONEY-150': 'Không phải kiểm thử (nhắc quy trình reset); đã có ở tiền điều kiện MUTATE',
    'TC-PERF-026': 'Trùng TC-GAME-079 (trần page tìm kiếm)',
    'TC-PERF-053': 'Trùng TC-PERF-050 (0 truy vấn SELECT body khi mở bài học)',
    'TC-PERF-057': 'Tập con TC-PERF-056 (mọi FK có index)',
    'TC-PERF-073': 'Trùng TC-GAME-077 (feed ?page > 1000)',
    'TC-PERF-081': 'Trùng TC-GAME-056 (thông báo xin vào chỉ tới owner/admin thật)',
    'TC-SECX-006': 'Trùng TC-INFRA-027 (Dockerfile NODE_ENV=production)',
    'TC-SECX-007': 'Trùng TC-SECX-001 (thiếu NODE_ENV bị chặn)',
    'TC-SECX-014': 'Trùng TC-SECX-009 và TC-INFRA-023 (checklist outbox 404)',
    'TC-SECX-017': 'Trùng TC-SECX-016/018/020: cùng vòng quét biến dev- trong productionEnvProblems (env.ts)',
    'TC-SECX-019': 'Trùng TC-SECX-016/018/020: cùng vòng quét biến dev- trong productionEnvProblems (env.ts)',
    'TC-SECX-029': 'Trùng TC-INFRA-051 (cảnh báo Redis khi nhiều instance)',
    'TC-SECX-032': 'Biến thể unit của TC-SECX-030',
    'TC-SECX-036': 'Biến thể unit của TC-SECX-035',
    'TC-SECX-053': 'Trùng ma trận TC-SECX-098..103 (cùng purpose, chạy đủ vai trò anonymous/chủ/ngoài/admin)',
    'TC-SECX-054': 'Trùng ma trận TC-SECX-098..103 (cùng purpose, chạy đủ vai trò anonymous/chủ/ngoài/admin)',
    'TC-SECX-055': 'Trùng ma trận TC-SECX-098..103 (cùng purpose, chạy đủ vai trò anonymous/chủ/ngoài/admin)',
    'TC-SECX-056': 'Trùng ma trận TC-SECX-098..103 (cùng purpose, chạy đủ vai trò anonymous/chủ/ngoài/admin)',
    'TC-SECX-057': 'Trùng ma trận TC-SECX-098..103 (cùng purpose, chạy đủ vai trò anonymous/chủ/ngoài/admin)',
    'TC-SECX-058': 'Trùng ma trận TC-SECX-098..103 (cùng purpose, chạy đủ vai trò anonymous/chủ/ngoài/admin)',
    'TC-SECX-113': 'Trùng TC-INFRA-016 (bảng env DEPLOY.md)',
    'TC-SECX-118': 'Trùng TC-SECX-035 (cookie HttpOnly/Path)',
    'TC-SECX-128': 'Không phải kiểm thử (quy trình khôi phục sau MUTATE) - đã ghi ở tiền điều kiện từng case',
    'TC-SECX-129': 'Trùng TC-SECX-023 (webhook khóa mặc định dev-)',
    'TC-SECX-130': 'Không phải kiểm thử (khẳng định không đổi TTL)',
    'TC-SPLIT-016': 'Mirror /communities ≡ /courses lặp: cùng communityAlias (backend/src/middlewares/community-alias.ts); giữ 013/014/017/020/026 đại diện',
    'TC-SPLIT-018': 'Mirror /communities ≡ /courses lặp: cùng communityAlias (backend/src/middlewares/community-alias.ts); giữ 013/014/017/020/026 đại diện',
    'TC-SPLIT-019': 'Mirror /communities ≡ /courses lặp: cùng communityAlias (backend/src/middlewares/community-alias.ts); giữ 013/014/017/020/026 đại diện',
    'TC-SPLIT-021': 'Mirror /communities ≡ /courses lặp: cùng communityAlias (backend/src/middlewares/community-alias.ts); giữ 013/014/017/020/026 đại diện',
    'TC-SPLIT-022': 'Mirror /communities ≡ /courses lặp: cùng communityAlias (backend/src/middlewares/community-alias.ts); giữ 013/014/017/020/026 đại diện',
    'TC-SPLIT-023': 'Mirror /communities ≡ /courses lặp: cùng communityAlias (backend/src/middlewares/community-alias.ts); giữ 013/014/017/020/026 đại diện',
    'TC-SPLIT-024': 'Mirror /communities ≡ /courses lặp: cùng communityAlias (backend/src/middlewares/community-alias.ts); giữ 013/014/017/020/026 đại diện',
    'TC-SPLIT-025': 'Mirror /communities ≡ /courses lặp: cùng communityAlias (backend/src/middlewares/community-alias.ts); giữ 013/014/017/020/026 đại diện',
    'TC-SPLIT-035': 'Redirect FE lặp: cùng LegacyCourseRedirect.tsx (App.tsx:57-58); giữ 033/034',
    'TC-SPLIT-036': 'Redirect FE lặp: cùng LegacyCourseRedirect.tsx (App.tsx:57-58); giữ 033/034',
    'TC-SPLIT-037': 'Redirect FE lặp: cùng LegacyCourseRedirect.tsx (App.tsx:57-58); giữ 033/034',
    'TC-SPLIT-038': 'Redirect FE lặp: cùng LegacyCourseRedirect.tsx (App.tsx:57-58); giữ 033/034',
    'TC-SPLIT-097': 'Trùng TC-ADM2-081 và 080 (chuyển trạng thái course admin, summary, 404/409/403)',
    'TC-SPLIT-098': "Trùng TC-ADM2-072 (tab Nháp liệt kê khóa nháp; sau cập nhật gồm 'Quản trị rủi ro (bản nháp)')",
    'TC-SPLIT-099': 'Trùng ma trận TC-ADM3-063/064 (/admin/content/* = content.manage, admin-staff.permissions.ts)',
    'TC-SPLIT-122': 'Trùng TC-SPLIT-039 (liên kết thông báo/email cũ qua redirect)',
    'TC-SPLIT-137': 'Trùng TC-SPLIT-134/135/136 (quét liên kết chết); kiểm bằng mã nguồn, không phải thao tác QA',
}
